on: [push]

jobs:
  build-coin:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: git clone https://aur.archlinux.org/coin.git $GITHUB_WORKSPACE

      - name: build package
        uses: jarias/makepkg-action@v1
        env:
          GPGKEY: arch@menari.io
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_PASSPHRASE: ${{ secrets.PASSPHRASE }}
          GPG_KEY_GRIP: ${{ secrets.GPG_KEY_GRIP }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET: arch.menari.io
          REPO: menari

  build-soqt:
    runs-on: ubuntu-latest
    needs:
      - build-coin
    steps:
      - name: checkout
        run: git clone https://aur.archlinux.org/soqt.git $GITHUB_WORKSPACE

      - name: build package
        uses: jarias/makepkg-action@v1
        env:
          GPGKEY: arch@menari.io
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_PASSPHRASE: ${{ secrets.PASSPHRASE }}
          GPG_KEY_GRIP: ${{ secrets.GPG_KEY_GRIP }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET: arch.menari.io
          REPO: menari

  build-python-pivy:
    runs-on: ubuntu-latest
    needs:
      - build-coin
      - build-soqt
    steps:
      - name: checkout
        run: git clone https://aur.archlinux.org/python-pivy.git $GITHUB_WORKSPACE

      - name: build package
        uses: jarias/makepkg-action@v1
        env:
          GPGKEY: arch@menari.io
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_PASSPHRASE: ${{ secrets.PASSPHRASE }}
          GPG_KEY_GRIP: ${{ secrets.GPG_KEY_GRIP }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET: arch.menari.io
          REPO: menari

  build-med:
    runs-on: ubuntu-latest
    needs:
      - build-python-pivy
    steps:
      - name: checkout
        run: git clone https://aur.archlinux.org/med.git $GITHUB_WORKSPACE

      - name: build package
        uses: jarias/makepkg-action@v1
        env:
          GPGKEY: arch@menari.io
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_PASSPHRASE: ${{ secrets.PASSPHRASE }}
          GPG_KEY_GRIP: ${{ secrets.GPG_KEY_GRIP }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET: arch.menari.io
          REPO: menari

  build-freecad:
    runs-on: ubuntu-latest
    needs:
      - build-python-pivy
      - build-coin
      - build-med
    steps:
      - name: checkout
        run: git clone https://aur.archlinux.org/freecad.git $GITHUB_WORKSPACE

      - name: build package
        uses: jarias/makepkg-action@v1
        env:
          GPGKEY: arch@menari.io
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_PASSPHRASE: ${{ secrets.PASSPHRASE }}
          GPG_KEY_GRIP: ${{ secrets.GPG_KEY_GRIP }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET: arch.menari.io
          REPO: menari

  build-google-chrome:
    runs-on: ubuntu-latest
    needs:
      - build-freecad
    steps:
      - name: checkout
        run: git clone https://aur.archlinux.org/google-chrome.git $GITHUB_WORKSPACE

      - name: build package
        uses: jarias/makepkg-action@v1
        env:
          GPGKEY: arch@menari.io
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_PASSPHRASE: ${{ secrets.PASSPHRASE }}
          GPG_KEY_GRIP: ${{ secrets.GPG_KEY_GRIP }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET: arch.menari.io
          REPO: menari

  build-zrepl:
    runs-on: ubuntu-latest
    needs:
      - build-google-chrome
    steps:
      - name: checkout
        run: git clone https://aur.archlinux.org/zrepl.git $GITHUB_WORKSPACE

      - name: build package
        uses: jarias/makepkg-action@v1
        env:
          GPGKEY: arch@menari.io
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_PASSPHRASE: ${{ secrets.PASSPHRASE }}
          GPG_KEY_GRIP: ${{ secrets.GPG_KEY_GRIP }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET: arch.menari.io
          REPO: menari

  build-obs-v4l2sink:
    runs-on: ubuntu-latest
    needs:
      - build-zrepl
    steps:
      - name: checkout
        run: git clone https://aur.archlinux.org/obs-v4l2sink.git $GITHUB_WORKSPACE

      - name: build package
        uses: jarias/makepkg-action@v1
        env:
          GPGKEY: arch@menari.io
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_PASSPHRASE: ${{ secrets.PASSPHRASE }}
          GPG_KEY_GRIP: ${{ secrets.GPG_KEY_GRIP }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET: arch.menari.io
          REPO: menari

  build-wlrobs-hg:
    runs-on: ubuntu-latest
    needs:
      - build-obs-v4l2sink
    steps:
      - name: checkout
        run: git clone https://aur.archlinux.org/wlrobs-hg.git $GITHUB_WORKSPACE

      - name: build package
        uses: jarias/makepkg-action@v1
        env:
          GPGKEY: arch@menari.io
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_PASSPHRASE: ${{ secrets.PASSPHRASE }}
          GPG_KEY_GRIP: ${{ secrets.GPG_KEY_GRIP }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET: arch.menari.io
          REPO: menari

  build-xlayoutdisplay:
    runs-on: ubuntu-latest
    needs:
      - build-wlrobs-hg
    steps:
      - name: checkout
        run: git clone https://aur.archlinux.org/xlayoutdisplay.git $GITHUB_WORKSPACE

      - name: build package
        uses: jarias/makepkg-action@v1
        env:
          GPGKEY: arch@menari.io
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEY_PASSPHRASE: ${{ secrets.PASSPHRASE }}
          GPG_KEY_GRIP: ${{ secrets.GPG_KEY_GRIP }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET: arch.menari.io
          REPO: menari
